[package]
name = "chat"
version = "0.1.0"
authors = ["AJTJ <janke.aaron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
actix-web = "3"
actix-web-actors = "3.0.0"
mysql = "20.1.0"